services:
  php:
    build:
      context: ./docker/php
      args:
        PUID: ${UID}
        PGID: ${GID}
    container_name: symfony_php_adeo_shop
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - PUID=${UID}
      - PGID=${GID}
      - HOME=/var/www/html
    user: "${UID}:${GID}"
    depends_on:
      - db
      - mailpit
    command: >
      bash -c "
        if [ ! -f /var/www/html/composer.json ]; then
          rm -rf /var/www/html/* /var/www/html/.*[!.]* 2>/dev/null || true &&
          composer create-project symfony/skeleton:\"7.3.x\" /tmp/symfony --no-interaction --prefer-dist &&
          cp -r /tmp/symfony/* /var/www/html/ &&
          cp -r /tmp/symfony/.* /var/www/html/ 2>/dev/null || true &&
          rm -rf /tmp/symfony &&
          cd /var/www/html &&
          composer install
        fi &&
        php-fpm"

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx_adeo_shop
    ports:
      - "8080:80"
      # - "8443:443" # Uncomment to expose HTTPS
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  db:
    image: mysql:8
    container_name: symfony_db_adeo_shop
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./mailpit/data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  worker:
    build:
      context: ./docker/php
      args:
        PUID: ${UID}
        PGID: ${GID}
    container_name: symfony_worker_adeo_shop
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - PUID=${UID}
      - PGID=${GID}
      - HOME=/var/www/html
    user: "${UID}:${GID}"
    depends_on:
      - db
      - mailpit
    command: php bin/console messenger:consume async --time-limit=3600

volumes:
  db_data:
