services:
  php:
    build:
      context: ./docker/php
      args:
        PUID: ${UID}
        PGID: ${GID}
    container_name: symfony_php_adeo_shop
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - PUID=${UID}
      - PGID=${GID}
      - HOME=/var/www/html
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://symfony:symfony@db:3306/symfony?serverVersion=8.0&charset=utf8mb4
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: symfony_nginx_adeo_shop
    ports:
      - "8080:80"
    volumes:
      - ./symfony:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    restart: unless-stopped

  db:
    image: mysql:8
    container_name: symfony_db_adeo_shop
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    restart: unless-stopped

  mailpit:
    image: axllent/mailpit
    container_name: mailpit
    restart: unless-stopped
    volumes:
      - ./mailpit/data:/data
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  worker:
    build:
      context: ./docker/php
      args:
        PUID: ${UID}
        PGID: ${GID}
    container_name: symfony_worker_adeo_shop
    volumes:
      - ./symfony:/var/www/html
    working_dir: /var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - PUID=${UID}
      - PGID=${GID}
      - HOME=/var/www/html
      - APP_ENV=dev
      - APP_DEBUG=1
      - DATABASE_URL=mysql://symfony:symfony@db:3306/symfony?serverVersion=8.0&charset=utf8mb4
    depends_on:
      db:
        condition: service_healthy
      php:
        condition: service_started
    restart: unless-stopped
    command: >
      bash -lc "
        if [ ! -f vendor/autoload_runtime.php ]; then
          composer install --no-interaction --prefer-dist
        fi &&
        # Wait a bit more for DB to be fully ready
        sleep 10 &&
        php bin/console messenger:consume async --time-limit=3600"

volumes:
  db_data:
