easy_admin:
    site_name: "Administration"

    formats:
        date: "d/m/Y"
        datetime: "d/m/Y H:i:s"

    design:
        brand:
            color: "#ffc107"

        assets:
            css:
                - "assets/app.css"

        color_scheme: "auto"
